# Very similar to the release build.
# Feel free to merge those into a single yaml
{
  'name': 'Manual Build',
  'on': ['workflow_dispatch'],
  'jobs':
    {
      'build-valetudo':
        {
          'runs-on': 'ubuntu-latest',
          'strategy': { 'matrix': { 'node-version': ['20.x'] } },
          'steps':
            [
              { 'uses': 'actions/checkout@v4' },
              {
                'name': 'Use Node.js ${{ matrix.node-version }}',
                'uses': 'actions/setup-node@v4',
                'with': { 'node-version': '${{ matrix.node-version }}' },
              },
              { 'name': 'Install', 'run': 'npm ci' },
              {
                'name': 'Generate OpenAPI Docs',
                'run': 'npm run build_openapi_schema',
              },
              {
                'name': 'Build Valetudo frontend',
                'run': 'npm run build --workspace=frontend',
              },
              {
                'name': 'Build Valetudo armv7',
                'run': 'npm run build_armv7 --workspace=backend',
              },
              {
                'name': 'Build Valetudo armv7 lowmem',
                'run': 'npm run build_armv7_lowmem --workspace=backend',
              },
              {
                'name': 'Build Valetudo aarch64',
                'run': 'npm run build_aarch64 --workspace=backend',
              },
              {
                'name': 'Build streamer.tar.gz',
                'run': 'npm run build:streamer',
              },

              {
                'name': 'Upload Valetudo armv7',
                'uses': 'actions/upload-artifact@v4',
                'with':
                  {
                    'name': 'valetudo-armv7',
                    'path': './build/armv7/valetudo',
                  },
              },
              {
                'name': 'Upload Valetudo armv7 lowmem',
                'uses': 'actions/upload-artifact@v4',
                'with':
                  {
                    'name': 'valetudo-armv7-lowmem',
                    'path': './build/armv7/valetudo-lowmem',
                  },
              },
              {
                'name': 'Upload Valetudo aarch64',
                'uses': 'actions/upload-artifact@v4',
                'with':
                  {
                    'name': 'valetudo-aarch64',
                    'path': './build/aarch64/valetudo',
                  },
              },
              {
                'name': 'Upload streamer.tar.gz',
                'uses': 'actions/upload-artifact@v4',
                'with':
                  {
                    'name': 'streamer.tar.gz',
                    'path': './build/streamer.tar.gz',
                  },
              },

              {
                'name': 'UPX-compress valetudo binaries',
                'run': 'npm run upx',
              },
              {
                'name': 'Upload Valetudo armv7.upx',
                'uses': 'actions/upload-artifact@v4',
                'with':
                  {
                    'name': 'valetudo-armv7.upx',
                    'path': './build/armv7/valetudo.upx',
                  },
              },
              {
                'name': 'Upload Valetudo armv7 lowmem.upx',
                'uses': 'actions/upload-artifact@v4',
                'with':
                  {
                    'name': 'valetudo-armv7-lowmem.upx',
                    'path': './build/armv7/valetudo-lowmem.upx',
                  },
              },
              {
                'name': 'Upload Valetudo aarch64.upx',
                'uses': 'actions/upload-artifact@v4',
                'with':
                  {
                    'name': 'valetudo-aarch64.upx',
                    'path': './build/aarch64/valetudo.upx',
                  },
              },

              {
                'name': 'Build manifest',
                'run': 'npm run build_release_manifest',
              },
              {
                'name': 'Upload manifest',
                'uses': 'actions/upload-artifact@v4',
                'with':
                  {
                    'name': 'valetudo_release_manifest.json',
                    'path': './build/valetudo_release_manifest.json',
                  },
              },
              
              {
                'name': 'Upload OpenAPI spec',
                'uses': 'actions/upload-artifact@v4',
                'with':
                  {
                    'name': 'valetudo.openapi.schema.json',
                    'path': './build/valetudo.openapi.schema.json',
                  },
              },
            ],
        },
    },
}
